project:
  name: Task_07_Decision_Making_Kunal_FULL
  random_seed: 42

data:
  raw_paths:
    - data/raw/lacrosse_stats.csv
  id_columns: ["player_id"]
  target_columns: ["goals","shots_on_goal","saves"]
  time_column: "match_minute"
  subgroup_columns: ["position","class_year"]

analysis:
  bootstrap:
    n_resamples: 2000
    ci_level: 0.95
  cross_validation:
    folds: 5
  outlier_z_threshold: 3.0
  missingness_threshold: 0.2

reporting:
  figures_dir: results/figures
  tables_dir: results/tables
  report_path: results/report/stakeholder_report.md
  label_llm_text: true
